name: Devops-Lab pipeline
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
          with:
           node-version: '14'
      - run: npm install
      - run: npm test
